# Generated by Django 3.2.19 on 2023-05-25 05:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import ratings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('code', models.CharField(max_length=5)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid_posted', models.IntegerField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=ratings.models.get_post_image_upload_path)),
                ('image_preview', models.ImageField(blank=True, upload_to=ratings.models.get_post_image_upload_path)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('restaurant_id', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('hex_identifier', models.CharField(default='no-hex', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImageDummies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dummyProfileImg')),
                ('image_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.TextField(blank=True)),
                ('title_image', models.ImageField(blank=True, upload_to='')),
                ('title_image_preview', models.ImageField(blank=True, upload_to='')),
                ('latitude_gps', models.TextField(blank=True)),
                ('longitude_gps', models.TextField(blank=True)),
                ('timestamp_gps', models.TextField(blank=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.TextField(blank=True)),
                ('instagram', models.TextField(blank=True)),
                ('facebook', models.TextField(blank=True)),
                ('street', models.TextField(blank=True)),
                ('zip', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('average_rating', models.TextField(blank=True)),
                ('qr_id', models.CharField(default=ratings.models.Restaurant.generate_qr_id, max_length=32)),
                ('tags', models.JSONField(default=list)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('user_firstname', models.TextField(blank=True)),
                ('user_lastname', models.TextField(blank=True)),
                ('profile_img', models.ImageField(blank=True, default='users/blankuser/profile_image.png', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_identifier', models.CharField(default='no-hex', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('restaurantid', models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='ratings.restaurant')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratings.user')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratings.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_identifier', models.CharField(default='no-hex', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.user')),
            ],
        ),
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_connected', models.BooleanField()),
                ('connection_type', models.CharField(max_length=100)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_identifier', models.CharField(default='no-hex', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visible_in_timeline', models.BooleanField(default=True)),
                ('commentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.post')),
                ('restaurantid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.restaurant')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.user')),
                ('userid_got_like', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userid_got_like', to='ratings.user')),
            ],
        ),
    ]
