# Generated by Django 4.2 on 2023-04-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid_posted', models.IntegerField(blank=True)),
                ('image_url', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('restaurant_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.TextField(blank=True)),
                ('image_url', models.TextField(blank=True)),
                ('latitude_gps', models.TextField(blank=True)),
                ('longitude_gps', models.TextField(blank=True)),
                ('timestamp_gps', models.TextField(blank=True)),
                ('telephone', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.TextField(blank=True)),
                ('instagram', models.TextField(blank=True)),
                ('facebook', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('log', models.JSONField(blank=True)),
            ],
        ),
    ]
