# Generated by Django 3.2.19 on 2023-05-20 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='userid_posted_comment',
        ),
        migrations.AddField(
            model_name='like',
            name='userid_got_like',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userid_got_like', to='ratings.user'),
        ),
    ]
