# Generated by Django 3.2.19 on 2023-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banana_points',
            field=models.IntegerField(default=0),
        ),
    ]
