# Generated by Django 3.2.19 on 2023-05-16 21:54

from django.db import migrations, models
import ratings.models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_remove_user_user_posts_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_preview_url',
            field=models.ImageField(blank=True, upload_to=ratings.models.get_post_image_upload_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_url',
            field=models.ImageField(blank=True, upload_to=ratings.models.get_post_image_upload_path),
        ),
    ]
