# Generated by Django 4.2 on 2023-04-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_restaurant_average_rating_restaurant_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.IntegerField(blank=True, default=1335906993),
            preserve_default=False,
        ),
    ]
