# Generated by Django 3.2.19 on 2023-05-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20230521_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindata',
            name='device_id',
        ),
    ]
