# Generated by Django 3.2.19 on 2023-05-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_remove_logindata_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
