# Generated by Django 4.2 on 2023-04-28 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_rename_name_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.post')),
                ('restaurantid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.restaurant')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.user')),
            ],
        ),
    ]
