# Generated by Django 4.2 on 2023-04-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_alter_user_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
