# Generated by Django 4.2 on 2023-04-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_remove_post_image_url_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
