# Generated by Django 4.2 on 2023-04-30 14:07

from django.db import migrations, models
import ratings.models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0011_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='qr_id',
            field=models.CharField(default='8e5663d9d47041f4b0632d4ce090a98a', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to=ratings.models.get_unique_image_filename),
            preserve_default=False,
        ),
    ]
