# Generated by Django 4.2 on 2023-04-30 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_restaurant_qr_id_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='qr_id',
            field=models.CharField(default='d84abe3db3874195bf25a1a4733a2f6a', max_length=32),
        ),
    ]
