# Generated by Django 4.2 on 2023-05-03 15:31

from django.db import migrations, models
import ratings.models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0013_remove_post_timestamp_post_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='log',
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.JSONField(default=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='qr_id',
            field=models.CharField(default=ratings.models.Restaurant.generate_qr_id, max_length=32),
        ),
    ]
