# Generated by Django 4.2 on 2023-05-09 13:51

from django.db import migrations, models
import ratings.models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0017_activationcode_phone_alter_activationcode_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_preview',
            field=models.ImageField(blank=True, upload_to=ratings.models.get_unique_image_filename),
        ),
    ]
