# Generated by Django 4.2 on 2023-05-09 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0018_post_image_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='userid',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.CASCADE, to='ratings.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_firstname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_lastname',
            field=models.TextField(blank=True),
        ),
    ]
