# Generated by Django 4.2 on 2023-05-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0019_restaurant_tags_restaurant_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
