# Generated by Django 4.2 on 2023-04-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='phone_number',
        ),
    ]
