# Generated by Django 4.2 on 2023-04-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_restaurants_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='photo_url',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
